<div class="bottom-form">
    <img src="<?= $block->getViewFileUrl('images/bullet.png') ?>" alt="">
    <div class="bottom-form-content">
        <div class="bottom-form-content-text">
            <div class="text-title">
                <span >TOP OF THE LINE GUARANTEE</span><br>
            </div>
            <div class="legend">
                <span > Premium Products for Superior Performance</span> <br>
            </div>
            <div class="field note">
                <span >Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat</span>
            </div>
        </div>
        <div class="actions-toolbar">
            <div class="primary">
                <input type="hidden" name="hideit" id="hideit" value="" />
                <button type="submit" title="<?= $block->escapeHtmlAttr(__('Start Shopping')) ?>" class="action submit primary">
                    <span><?= $block->escapeHtml(__('Start Shopping')) ?></span>
                </button>
            </div>
        </div>
    </div>

</div>