<div class="left-form">
    <div class="left-form-contact">
        <div class="left-form-contact-wrap">
            <div class="title-contact">
                <span>Pilgrim Ammunition Inc</span>
            </div>
            <div class="content-contact">
                <div class="content-mail"><i class="fas fa-envelope"></i><span>contact@pilgrimammunition.com</span></div>
                <div class="content-address"><i class="fas fa-map-marker-alt"></i><span>1880 University Parkway, Sarasota, FL 34243</span></div>
            </div>
        </div>


    </div>
    <div class="left-form-map">
        <img class="my-banner" src="<?php echo $block->getViewFileUrl('images/map.png'); ?>" />
    </div>
</div>