<div class="left-form">
    <div class="left-form-contact">
        <div class="left-form-contact-wrap">
            <div class="title-contact">
                <span>Pilgrim Ammunition Inc</span>
            </div>
            <ul class="content-contact">
                <li>
                    <i class="far fa-envelope"></i><span>contact@pilgrimammunition.com</span>
                </li>
                <li>
                    <i class="fas fa-map-marker-alt"></i>
                    <span>1880 University Parkway, Sarasota, FL 34243</span>
                </li>
            </ul>
        </div>
    </div>
    <div class="left-form-map">
        <img class="my-banner" src="<?php echo $block->getViewFileUrl('images/map.png'); ?>" />
    </div>
</div>